/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Machine Learning (ML) library - BPF trace context struct definitions
 *
 * Manually mirrors the trace_event_raw_* structs generated by the kernel's
 * TRACE_EVENT() macros (include/trace/events/ml_lib.h and ml_lib_test.h).
 * Required when compiling BPF programs against vmlinux.h from a kernel that
 * does not have the ml_lib module compiled in.
 *
 * Layout rules:
 *   - First field: struct trace_entry ent  (standard trace header)
 *   - __field(T, name)   -> T name
 *   - __string(name, ..) -> u32 __data_loc_name  (offset/len packed word)
 *   - Terminated by:     char __data[]
 *
 * Copyright (C) 2025-2026 Viacheslav Dubeyko <slava@dubeyko.com>
 */

#ifndef _ML_LIB_TRACE_TYPES_H
#define _ML_LIB_TRACE_TYPES_H

/*
 * These structs are only needed when vmlinux.h was generated from a kernel
 * that does not have the ml_lib module compiled in.  If the running kernel
 * already has ml_lib BTF data, bpftool will have emitted these structs into
 * vmlinux.h and re-defining them here would cause a redefinition error.
 *
 * The Makefile detects this situation and passes -DML_LIB_TYPES_IN_VMLINUX
 * so the block below is skipped.
 */
#ifndef ML_LIB_TYPES_IN_VMLINUX

/* ml_lib:ml_lib_model_registered */
struct trace_event_raw_ml_lib_model_registered {
	struct trace_entry ent;
	__u32 model_id;
	__u32 __data_loc_subsystem_name;
	__u32 __data_loc_model_name;
	char __data[];
};

/* ml_lib:ml_lib_model_unregistered */
struct trace_event_raw_ml_lib_model_unregistered {
	struct trace_entry ent;
	__u32 model_id;
	char __data[];
};

/* ml_lib:ml_lib_state_change */
struct trace_event_raw_ml_lib_state_change {
	struct trace_entry ent;
	__u32 model_id;
	int old_state;
	int new_state;
	char __data[];
};

/* ml_lib:ml_lib_dataset_update */
struct trace_event_raw_ml_lib_dataset_update {
	struct trace_entry ent;
	__u32 model_id;
	int dataset_type;
	int dataset_state;
	char __data[];
};

/* ml_lib_test:ml_lib_test_dev_access */
struct trace_event_raw_ml_lib_test_dev_access {
	struct trace_entry ent;
	unsigned long access_count;
	char __data[];
};

/* ml_lib_test:ml_lib_test_dev_io */
struct trace_event_raw_ml_lib_test_dev_io {
	struct trace_entry ent;
	int op_type;
	unsigned long bytes;
	unsigned long count;
	char __data[];
};

#endif /* !ML_LIB_TYPES_IN_VMLINUX */

#endif /* _ML_LIB_TRACE_TYPES_H */
